name: Doc Request
description: Request a new documentation for OmniFabric
title: "[Doc Request]: "
labels: [kind/doc_request]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue about this doc request?
      description: Please check if an issue already exists for the doc request proposal.
      options:
        - label: I have checked the existing issues.
          required: true
  - type: textarea
    attributes:
      label: Describe the doc request.
      description: |
        Why is this doc required for OmniFabric? How does it help developers?
    validations:
      required: true
